{"name": "test_login_with_invalid_user", "status": "passed", "start": 1751908808255, "stop": 1751908810400, "uuid": "d1209c8d-c0a2-4e66-98f9-783217495a7d", "historyId": "0e4edb4712d043b1bc1ffb1b2129d6cf", "testCaseId": "0e4edb4712d043b1bc1ffb1b2129d6cf", "fullName": "testcase.test_login.TestLogin#test_login_with_invalid_user", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-CIEP9G2C"}, {"name": "thread", "value": "9452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}